# =============================================================================
# SoCal Food Influencer Google Dorks - FINAL COMBINED LIST
# =============================================================================

DORK_QUERIES_LIST = [
    'site:instagram.com "213" "LA" "foodie" -inurl:explore',
    'site:instagram.com "24 hour" "LA" "food" -inurl:explore',
    'site:instagram.com "30th Street" "San Diego" "food" -inurl:explore',
    'site:instagram.com "310" "foodie" "LA" -inurl:explore',
    'site:instagram.com "323" "food blogger" "Los Angeles" -inurl:tags',
    'site:instagram.com "4th Street Market" "DTSA" "foodie" -inurl:explore',
    'site:instagram.com "4th Street Market" "foodie" -inurl:tags',
    'site:instagram.com "619" "San Diego" "foodie" -inurl:tags',
    'site:instagram.com "619" "foodie" -inurl:explore',
    'site:instagram.com "626 Night Market" "foodie" "Arcadia" -inurl:explore',
    'site:instagram.com "626 Night Market" "foodie" -inurl:explore',
    'site:instagram.com "626 Night Market" -inurl:explore',
    'site:instagram.com "626" "foodie" "SGV" -inurl:explore',
    'site:instagram.com "626" "foodie" "eats" -inurl:explore',
    'site:instagram.com "626" "foodie" -inurl:explore',
    'site:instagram.com "714" "Orange County" "food blogger" -inurl:explore',
    'site:instagram.com "760" "foodie" -inurl:explore',
    'site:instagram.com "818" "foodie" "content" -inurl:tags',
    'site:instagram.com "858" "SD" "food content" -inurl:explore',
    'site:instagram.com "858" "foodie" -inurl:explore',
    'site:instagram.com "909" "foodie" -inurl:explore',
    'site:instagram.com "949" "OC" "foodie" -inurl:tags',
    'site:instagram.com "951" "foodie" -inurl:explore',
    'site:instagram.com "@yelp" "elite" "LA" -inurl:explore',
    'site:instagram.com "@yelp" "elite" "OC" -inurl:explore',
    'site:instagram.com "Abbot Kinney" "food" "LA" -inurl:tags',
    'site:instagram.com "Alameda Night Market" "LA" "food" -inurl:tags',
    'site:instagram.com "Alhambra" "food" "blogger" -inurl:explore',
    'site:instagram.com "Alhambra" "food" "blogger" -inurl:tags',
    'site:instagram.com "Alhambra" "foodie" -inurl:explore',
    'site:instagram.com "Aliso Viejo" "food" -inurl:explore',
    'site:instagram.com "Anaheim Packing District" "foodie" "OC" -inurl:explore',
    'site:instagram.com "Anaheim Packing District" "foodie" -inurl:tags',
    'site:instagram.com "Anaheim" "food" "blogger" -inurl:tags',
    'site:instagram.com "Anaheim" "foodie" "OC" -inurl:tags',
    'site:instagram.com "Anaheim" "foodie" -inurl:explore',
    'site:instagram.com "Apple Valley" "CA" "food" -inurl:explore',
    'site:instagram.com "Arcadia" "dining" "626" -inurl:explore',
    'site:instagram.com "Arcadia" "food" -inurl:explore',
    'site:instagram.com "Arcadia" "foodie" "content" -inurl:explore',
    'site:instagram.com "Argentinian food" "LA" -inurl:explore',
    'site:instagram.com "Armenian food" "LA" -inurl:explore',
    'site:instagram.com "Armenian" "Glendale" "food" -inurl:explore',
    'site:instagram.com "Arts District" "LA" "dining" -inurl:explore',
    'site:instagram.com "Arts District" "LA" "food" -inurl:explore',
    'site:instagram.com "Arts District" "foodie" -inurl:explore',
    'site:instagram.com "Atwater Village" "bakery" "foodie" -inurl:tags',
    'site:instagram.com "Atwater Village" "food" -inurl:explore',
    'site:instagram.com "Atwater Village" "foodie" -inurl:explore',
    'site:instagram.com "Ave 26 Night Market" "tacos" "LA" -inurl:explore',
    'site:instagram.com "Azusa" "food" -inurl:explore',
    'site:instagram.com "Barrio Logan" "food" -inurl:explore',
    'site:instagram.com "Barrio Logan" "foodie" -inurl:explore',
    'site:instagram.com "Barrio Logan" "tacos" "SD" -inurl:tags',
    'site:instagram.com "Bellflower" "foodie" -inurl:explore',
    'site:instagram.com "Belmont Shore" "food" -inurl:explore',
    'site:instagram.com "Beverly Grove" "food" -inurl:explore',
    'site:instagram.com "Beverly Hills" "foodie" "luxury" -inurl:explore',
    'site:instagram.com "Beverly Hills" "foodie" -inurl:explore',
    'site:instagram.com "Boyle Heights" "foodie" -inurl:explore',
    'site:instagram.com "Boyle Heights" "street food" "LA" -inurl:explore',
    'site:instagram.com "Brazilian food" "LA" -inurl:explore',
    'site:instagram.com "Brea" "food" "content creator" -inurl:tags',
    'site:instagram.com "Brea" "food" -inurl:explore',
    'site:instagram.com "Brentwood" "LA" "food" -inurl:explore',
    'site:instagram.com "Brentwood" "food" -inurl:explore',
    'site:instagram.com "Brentwood" "foodie" "LA" -inurl:explore',
    'site:instagram.com "Buena Park" "Korean food" "OC" -inurl:tags',
    'site:instagram.com "Buena Park" "food" -inurl:explore',
    'site:instagram.com "Burbank" "foodie" -inurl:explore',
    'site:instagram.com "CSULB" "food" "Long Beach" -inurl:explore',
    'site:instagram.com "Cal Poly Pomona" "foodie" "CPP" -inurl:tags',
    'site:instagram.com "Calabasas" "foodie" -inurl:explore',
    'site:instagram.com "Cantonese" "LA" "food" -inurl:explore',
    'site:instagram.com "Carlsbad" "eats" "North County" -inurl:explore',
    'site:instagram.com "Carlsbad" "food" "content" -inurl:tags',
    'site:instagram.com "Carlsbad" "food" -inurl:explore',
    'site:instagram.com "Carson" "foodie" -inurl:explore',
    'site:instagram.com "Cerritos" "foodie" -inurl:explore',
    'site:instagram.com "Chinatown" "LA" "food" -inurl:explore',
    'site:instagram.com "Chinatown" "LA" "foodie" -inurl:explore',
    'site:instagram.com "Chinese food" "626" -inurl:explore',
    'site:instagram.com "Chinese food" "LA" "foodie" -inurl:explore',
    'site:instagram.com "Chinese food" "SGV" "626" -inurl:tags',
    'site:instagram.com "Chinese food" "SGV" -inurl:explore',
    'site:instagram.com "Chino Hills" "foodie" "IE" -inurl:tags',
    'site:instagram.com "Chino Hills" "foodie" -inurl:explore',
    'site:instagram.com "Chino" "food" -inurl:explore',
    'site:instagram.com "Chula Vista" "food" -inurl:explore',
    'site:instagram.com "Chula Vista" "foodie" "tacos" -inurl:explore',
    'site:instagram.com "Citizen Public Market" "Culver City" "food" -inurl:explore',
    'site:instagram.com "Claremont" "dining" "Village" -inurl:tags',
    'site:instagram.com "Claremont" "food" -inurl:explore',
    'site:instagram.com "Coachella Valley" "food" -inurl:explore',
    'site:instagram.com "Colombian food" "LA" -inurl:explore',
    'site:instagram.com "Colton" "foodie" -inurl:explore',
    'site:instagram.com "Convoy District" "food" "Asian" -inurl:tags',
    'site:instagram.com "Convoy District" "food" -inurl:tags',
    'site:instagram.com "Convoy District" "foodie" -inurl:explore',
    'site:instagram.com "Convoy" "SD" "eats" -inurl:tags',
    'site:instagram.com "Convoy" "SD" "food" -inurl:explore',
    'site:instagram.com "Convoy" "San Diego" "foodie" -inurl:explore',
    'site:instagram.com "Convoy" "food" "content creator" -inurl:tags',
    'site:instagram.com "Convoy" "ramen" "content creator" "DM" -inurl:tags',
    'site:instagram.com "Corona" "CA" "food" -inurl:explore',
    'site:instagram.com "Corona" "eats" "IE" -inurl:explore',
    'site:instagram.com "Corporation Food Hall" "DTLA" "foodie" -inurl:tags',
    'site:instagram.com "Costa Mesa" "eats" "OC" -inurl:explore',
    'site:instagram.com "Costa Mesa" "eats" "content" -inurl:explore',
    'site:instagram.com "Costa Mesa" "food blogger" -inurl:tags',
    'site:instagram.com "Costa Mesa" "food" -inurl:explore',
    'site:instagram.com "Costa Mesa" "foodie" -inurl:explore',
    'site:instagram.com "Covina" "foodie" -inurl:explore',
    'site:instagram.com "Crenshaw" "foodie" -inurl:explore',
    'site:instagram.com "Cuban food" "LA" -inurl:explore',
    'site:instagram.com "Culver City" "eats" "blogger" -inurl:explore',
    'site:instagram.com "Culver City" "food blogger" -inurl:tags',
    'site:instagram.com "Culver City" "foodie" -inurl:explore',
    'site:instagram.com "Cypress" "food" -inurl:explore',
]
